import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/configs/providers";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata = () => {
  return {
    title: 'Flight Search - Your Airline',
    description: 'Search for flights with ease and find the best deals.',
    openGraph: {
      title: 'Flight Search - Your Airline',
      description: 'Search for flights with ease and find the best deals.',
      url: 'https://your-website.com/flight/search',
      siteName: 'Your Airline',
      images: [
        {
          url: 'https://your-website.com/og-image.jpg',
          width: 800,
          height: 600,
          alt: 'Og Image Alt',
        },
      ],
      type: 'website',
    },
    twitter: {
      card: 'summary_large_image',
      title: 'Flight Search - Your Airline',
      description: 'Search for flights with ease and find the best deals.',
      site: '@YourAirline',
      creator: '@YourAirline',
    },
  };
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactElement;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
